name: Protect Main Branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  protect_main_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Protect Main Branch
        uses: actions/github-script@v2
        with:
          script: |
            const octokit = require('@octokit/rest')({ auth: process.env.GITHUB_TOKEN });
            const { data } = await octokit.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main'
            });

            if (data.required_status_checks === null) {
              await octokit.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main',
                required_status_checks: { strict: true, contexts: [] },
                enforce_admins: true,
                restrictions: null
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
