name: Update Mergeability

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update_mergeability:
    runs-on: ubuntu-latest

    steps:
      - name: wait
        run: sleep 100
