name: Hotfix Workflow

on:
  push:
    branches:
      - hotfix

env:
  BRANCH_NAME: ${{ github.ref }}

jobs:
  disallow_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Get original branch protection settings
        id: get_protection_settings
        run: |
          curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection > protection.json

      - name: Lock main branch
        run: |
          curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{"required_pull_request_reviews": {"dismissal_restrictions": {"users": ["'${{ github.actor }}'"], "teams": []}, "dismissal_approvals": {"users": ["'${{ github.actor }}'"], "teams": []}}}'

      - name: Wait for workflow to complete
        run: |
          echo "The workflow is running. Please wait until it is complete before attempting to merge or approve pull requests to the main branch."
          sleep 100

      - name: Revert original branch protection settings
        run: |
          curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection/required_pull_request_reviews \
          -d "$(cat protection.json | jq '.required_pull_request_reviews')"
