name: Block Merge on Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check conditions
        run: |
          echo This check blocks the merge.
          exit 1
