name: Block Merge on Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check conditions
        run: |
          echo This check blocks the merge.
          exit 1
      - name: Set Pull Request status
        if: failure()
        uses: peter-evans/set-pull-request-status@v1
        with:
          state: failure
          description: The pull request failed the checks
          context: Continuous Integration
