name: Block Merge on Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check conditions
        run: |
          echo This check blocks the merge.
          exit 1
      - name: Set Pull Request status
        if: failure()
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const octokit = require("@octokit/rest")();
            octokit.authenticate({
              type: "token",
              token: process.env.GITHUB_TOKEN
            });
            await octokit.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "failure",
              description: "The pull request failed the checks",
              context: "Continuous Integration"
            });
