name: Protect Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          # Your checks go here
          echo "Running checks..."

      - name: Update status
        uses: octokit/request-action@v2
        with:
          octokit_auth: ${{ secrets.GITHUB_TOKEN }}
          octokit_event_path: ${{ github.event_path }}
          method: POST
          url: https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          headers:
            accept: application/vnd.github.antiope-preview+json
          payload: |
            {
              "state": "success",
              "context": "checks",
              "description": "All checks have passed"
            }

      - name: Update mergeability
        uses: octokit/request-action@v2
        with:
          octokit_auth: ${{ secrets.GITHUB_TOKEN }}
          octokit_event_path: ${{ github.event_path }}
          method: PATCH
          url: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
          headers:
            accept: application/vnd.github.v3+json
          payload: |
            {
              "state": "success",
              "mergeable": true
            }
